### ISSUE TITLE
createTasks.py: error: no such option: -u

### ISSUE THREAD

**Issue by misaka-10032** [PyBossa/app-tagging-pictures#1]
Maybe readme.md is not updated? Thx!

**Comment by teleyinex** [comment]
Hi,

Yes, you are right. I would recommend you to use [PBS](https://github.com/PyBossa/pbs) instead of createTasks.py as it's a complete command line utility to control your PyBossa project. Please, check the documentation of pbs and then try it. We'll update it here in the meantime.

Cheers
